# Generated by Django 6.1.1 on 2026-09-19 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment')], max_length=12)),
                ('quantity', models.IntegerField(help_text='Positive for stock in, negative for stock out')),
                ('previous_stock', models.PositiveIntegerField()),
                ('new_stock', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, help_text='e.g. PUR-00001 / INV-00001', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
