# Generated by Django 6.1.1 on 2026-09-19 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('DAILY', 'Daily'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=10)),
                ('forecast_date', models.DateField(help_text='The future period being forecast')),
                ('estimated_revenue', models.DecimalField(decimal_places=2, max_digits=14)),
                ('model_used', models.CharField(default='Linear Regression', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
